# Generated by Django 5.0.7 on 2024-07-27 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sizes',
            new_name='Size',
        ),
    ]
