# Generated by Django 5.0.7 on 2024-08-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cartitem_alter_cart_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='products',
            new_name='product',
        ),
    ]
