# Generated by Django 5.0.7 on 2024-08-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_products_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
