# Generated by Django 5.0.7 on 2024-08-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_productjourney'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductJourney',
        ),
    ]
