# Generated by Django 5.0.7 on 2024-08-04 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_product_bought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productjourney',
            name='journey',
        ),
        migrations.AddField(
            model_name='productjourney',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.DeleteModel(
            name='Journey',
        ),
    ]
