# Generated by Django 5.0.7 on 2024-08-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_productjourney_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
    ]
