# Generated by Django 5.0.7 on 2024-08-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_productjourney_to_productjourney_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productjourney',
            name='action',
            field=models.CharField(choices=[('buy', 'buy'), ('donate', 'donate'), ('claim', 'claim')], default='claim', max_length=255),
            preserve_default=False,
        ),
    ]
