# Generated by Django 5.0.7 on 2024-08-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_productjourney_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
